CC = gcc

all : multithread_practice_solve multithread_practice

multithread_practice_solve: multithread_practice_solve.c
	$(CC) -o $@ $< -lpthread

multithread_practice: multithread_practice.c
	$(CC) -o $@ $< -lpthread
